"""
 * Nom de l'application : CyberConfiance
 * Description : Fichier ai_patterns_analyzer.py du projet CyberConfiance
 * Produit de : MOA Digital Agency, www.myoneart.com
 * Fait par : Aisance KALONJI, www.aisancekalonji.com
 * Auditer par : La CyberConfiance, www.cyberconfiance.com

"""

"""
CyberConfiance
By MOA Digital Agency LLC
Developed by: Aisance KALONJI
Contact: moa@myoneart.com
www.myoneart.com

Detecteur de patterns de code genere par IA (vibecoding).
"""

from typing import List, Dict, Any
from .base_analyzer import BaseAnalyzer


class AIPatternAnalyzer(BaseAnalyzer):
    
    TOXIC_AI_PATTERNS = [
        (r'# TODO:?\s*(fix|implement|add|complete|finish|later)', 'TODO non résolu', 'low', "Compléter l'implémentation ou supprimer le TODO"),
        (r'// TODO:?\s*(fix|implement|add|complete|finish|later)', 'TODO non résolu (JS)', 'low', "Compléter l'implémentation"),
        (r'# FIXME', 'FIXME non résolu', 'medium', "Corriger le problème signalé par FIXME"),
        (r'// FIXME', 'FIXME non résolu (JS)', 'medium', "Corriger le problème signalé"),
        (r'# HACK', 'Code hack temporaire', 'medium', "Refactoriser pour une solution propre"),
        (r'# XXX', 'XXX marker non résolu', 'medium', "Résoudre le problème marqué XXX"),
        (r'pass\s*# ?(placeholder|todo|implement|fix)', 'Placeholder pass statement', 'medium', "Implémenter la fonctionnalité"),
        (r'raise NotImplementedError', 'Fonction non implémentée', 'medium', "Implémenter la méthode"),
        (r'throw\s+new\s+Error\s*\(\s*["\']Not\s+implemented', 'Fonction non implémentée (JS)', 'medium', "Implémenter la fonction"),
        (r'print\s*\(["\']debug', 'Debug print laissé', 'low', "Supprimer les prints de debug"),
        (r'print\s*\(["\']test', 'Test print laissé', 'low', "Supprimer les prints de test"),
        (r'console\.log\s*\(["\']debug', 'Debug console.log', 'low', "Supprimer les console.log de debug"),
        (r'console\.log\s*\(["\']test', 'Test console.log', 'low', "Supprimer les console.log de test"),
        (r'debugger;', 'Debugger statement laissé', 'medium', "Supprimer le debugger statement"),
        (r'\.\.\..*# ?generated', 'Code généré non vérifié', 'medium', "Vérifier le code généré par IA"),
        (r'except:\s*pass', 'Exception silencieuse', 'high', "Gérer l'exception correctement ou au minimum logger"),
        (r'except\s+Exception\s*:\s*pass', 'Exception générique silencieuse', 'high', "Capturer des exceptions spécifiques et les gérer"),
        (r'except\s+Exception\s+as\s+\w+:\s*pass', 'Exception capturée mais ignorée', 'high', "Logger l'exception ou la gérer"),
        (r'catch\s*\(\s*\w*\s*\)\s*\{\s*\}', 'Catch block vide', 'high', "Gérer l'erreur ou au minimum la logger"),
        (r'# AI generated|# Generated by|# Auto-generated', 'Code AI non vérifié', 'info', "Vérifier et tester le code généré par IA"),
        (r'// AI generated|// Generated by|// Auto-generated', 'Code AI non vérifié (JS)', 'info', "Vérifier et tester le code généré"),
        (r'# copilot|# chatgpt|# claude', 'Code généré par IA', 'info', "S'assurer que le code a été revu"),
        (r'def\s+\w+\s*\([^)]*\)\s*:\s*\.\.\.\s*$', 'Fonction stub incomplète', 'medium', "Implémenter le corps de la fonction"),
        (r'return\s+None\s*# ?todo', 'Return placeholder', 'medium', "Implémenter le retour correct"),
        (r'return\s+\[\s*\]\s*# ?todo', 'Return liste vide placeholder', 'medium', "Implémenter le retour correct"),
        (r'return\s+\{\s*\}\s*# ?todo', 'Return dict vide placeholder', 'medium', "Implémenter le retour correct"),
        (r'# This is a (simple|basic|dummy|test) implementation', 'Implémentation temporaire', 'medium', "Remplacer par une implémentation production-ready"),
        (r'// This is a (simple|basic|dummy|test) implementation', 'Implémentation temporaire (JS)', 'medium', "Remplacer par une implémentation robuste"),
        (r'# Replace this with', 'Code à remplacer', 'medium', "Remplacer le code comme indiqué"),
        (r'// Replace this with', 'Code à remplacer (JS)', 'medium', "Remplacer le code comme indiqué"),
        (r'lorem\s*ipsum', 'Texte placeholder Lorem Ipsum', 'low', "Remplacer par du vrai contenu"),
        (r'foo|bar|baz|qux', 'Noms de variables génériques', 'info', "Utiliser des noms de variables descriptifs"),
    ]
    
    DUPLICATE_CODE_PATTERNS = [
        (r'def\s+(\w+)\s*\([^)]*\).*\n.*\n.*\ndef\s+\1_\w+\s*\([^)]*\)', 'Fonctions similaires potentiellement dupliquées', 'low', "Considérer la factorisation du code dupliqué"),
    ]
    
    def analyze(self, content: str, filepath: str, lines: List[str] = None) -> List[Dict[str, Any]]:
        self.findings = []
        
        self.findings.extend(self._scan_patterns(content, filepath, self.TOXIC_AI_PATTERNS, 'toxic_ai'))
        self.findings.extend(self._scan_patterns(content, filepath, self.DUPLICATE_CODE_PATTERNS, 'duplicate'))
        
        return self.findings
